### ISSUE TITLE
本番環境（Heroku）にpush出来ない

### ISSUE THREAD

**Issue by O-H-K-N** [O-H-K-N/walk-tour-rails#21]
## 実現したいこと

Vue（フロント）× Rails API（サーバ）でアプリを開発中。
VueをFirebase、Rails APIをHerokuにデプロイしたい。

## 現状発生している問題・エラーメッセージ

Rails APIをHerokuにデプロイできない

> ターミナルでのエラー文
> ```
> remote: -----> Preparing app for Rails asset pipeline
> remote:        Running: rake assets:precompile
> remote:        rake aborted!
> remote:        Sprockets::FileNotFound: couldn't find file 'admin-lte/plugins/bootstrap/js/bootstrap.bundle.min' with type 'application/javascript'
> remote:        Checked in these paths:
> remote:          /tmp/build_bdc47327/app/assets/config
> remote:          /tmp/build_bdc47327/app/assets/javascript
> remote:          /tmp/build_bdc47327/app/assets/stylesheets
> remote:          /tmp/build_bdc47327/vendor/bundle/ruby/2.6.0/gems/jquery-rails-4.5.0/vendor/assets/javascripts
> remote:          /tmp/build_bdc47327/vendor/bundle/ruby/2.6.0/gems/coffee-rails-4.2.2/lib/assets/javascripts
> remote:          /tmp/build_bdc47327/vendor/bundle/ruby/2.6.0/gems/actioncable-6.1.6/app/assets/javascripts
> remote:          /tmp/build_bdc47327/vendor/bundle/ruby/2.6.0/gems/activestorage-6.1.6/app/assets/javascripts
> remote:          /tmp/build_bdc47327/vendor/bundle/ruby/2.6.0/gems/actionview-6.1.6/lib/assets/compiled
> remote:          /tmp/build_bdc47327/node_modules
> remote:          /tmp/build_bdc47327/vendor/bundle/ruby/2.6.0/gems/font-awesome-sass-5.11.2/assets/stylesheets
> remote:          /tmp/build_bdc47327/vendor/bundle/ruby/2.6.0/gems/font-awesome-sass-5.11.2/assets/fonts
> remote:          /tmp/build_bdc47327/vendor/bundle/ruby/2.6.0/gems/popper_js-1.16.0/assets/javascripts
> remote:          /tmp/build_bdc47327/vendor/bundle/ruby/2.6.0/gems/bootstrap-4.5.3/assets/stylesheets
> remote:          /tmp/build_bdc47327/vendor/bundle/ruby/2.6.0/gems/bootstrap-4.5.3/assets/javascripts
> remote:        /tmp/build_bdc47327/app/assets/javascript/admin.js:3
> remote:        /tmp/build_bdc47327/vendor/bundle/ruby/2.6.0/gems/sprockets-4.0.3/lib/sprockets/resolve.rb:62:in `resolve!'
> remote:        /tmp/build_bdc47327/vendor/bundle/ruby/2.6.0/gems/sprockets-4.0.3/lib/sprockets/directive_processor.rb:409:in `resolve'
> remote:        /tmp/build_bdc47327/vendor/bundle/ruby/2.6.0/gems/sprockets-4.0.3/lib/sprockets/directive_processor.rb:216:in `process_require_directive'
> remote:        /tmp/build_bdc47327/vendor/bundle/ruby/2.6.0/gems/sprockets-4.0.3/lib/sprockets/directive_processor.rb:189:in `block in process_directives'
> remote:        /tmp/build_bdc47327/vendor/bundle/ruby/2.6.0/gems/sprockets-4.0.3/lib/sprockets/directive_processor.rb:187:in `each'
> remote:        /tmp/build_bdc47327/vendor/bundle/ruby/2.6.0/gems/sprockets-4.0.3/lib/sprockets/directive_processor.rb:187:in `process_directives'
> remote:        /tmp/build_bdc47327/vendor/bundle/ruby/2.6.0/gems/sprockets-4.0.3/lib/sprockets/directive_processor.rb:84:in `_call'
> remote:        /tmp/build_bdc47327/vendor/bundle/ruby/2.6.0/gems/sprockets-4.0.3/lib/sprockets/directive_processor.rb:65:in `call'
> remote:        /tmp/build_bdc47327/vendor/bundle/ruby/2.6.0/gems/sprockets-4.0.3/lib/sprockets/processor_utils.rb:84:in `call_processor'
> remote:        /tmp/build_bdc47327/vendor/bundle/ruby/2.6.0/gems/sprockets-4.0.3/lib/sprockets/processor_utils.rb:66:in `block in call_processors'
> remote:        /tmp/build_bdc47327/vendor/bundle/ruby/2.6.0/gems/sprockets-4.0.3/lib/sprockets/processor_utils.rb:65:in `reverse_each'
> remote:        /tmp/build_bdc47327/vendor/bundle/ruby/2.6.0/gems/sprockets-4.0.3/lib/sprockets/processor_utils.rb:65:in `call_processors'
> remote:        /tmp/build_bdc47327/vendor/bundle/ruby/2.6.0/gems/sprockets-4.0.3/lib/sprockets/loader.rb:182:in `load_from_unloaded'
> remote:        /tmp/build_bdc47327/vendor/bundle/ruby/2.6.0/gems/sprockets-4.0.3/lib/sprockets/loader.rb:59:in `block in load'
> remote:        /tmp/build_bdc47327/vendor/bundle/ruby/2.6.0/gems/sprockets-4.0.3/lib/sprockets/loader.rb:337:in `fetch_asset_from_dependency_cache'
> remote:        /tmp/build_bdc47327/vendor/bundle/ruby/2.6.0/gems/sprockets-4.0.3/lib/sprockets/loader.rb:43:in `load'
> remote:        /tmp/build_bdc47327/vendor/bundle/ruby/2.6.0/gems/sprockets-4.0.3/lib/sprockets/cached_environment.rb:44:in `load'
> remote:        /tmp/build_bdc47327/vendor/bundle/ruby/2.6.0/gems/sprockets-4.0.3/lib/sprockets/bundle.rb:27:in `call'
> remote:        /tmp/build_bdc47327/vendor/bundle/ruby/2.6.0/gems/sprockets-4.0.3/lib/sprockets/processor_utils.rb:84:in `call_processor'
> remote:        /tmp/build_bdc47327/vendor/bundle/ruby/2.6.0/gems/sprockets-4.0.3/lib/sprockets/processor_utils.rb:66:in `block in call_processors'
> remote:        /tmp/build_bdc47327/vendor/bundle/ruby/2.6.0/gems/sprockets-4.0.3/lib/sprockets/processor_utils.rb:65:in `reverse_each'
> remote:        /tmp/build_bdc47327/vendor/bundle/ruby/2.6.0/gems/sprockets-4.0.3/lib/sprockets/processor_utils.rb:65:in `call_processors'
> remote:        /tmp/build_bdc47327/vendor/bundle/ruby/2.6.0/gems/sprockets-4.0.3/lib/sprockets/loader.rb:182:in `load_from_unloaded'
> remote:        /tmp/build_bdc47327/vendor/bundle/ruby/2.6.0/gems/sprockets-4.0.3/lib/sprockets/loader.rb:59:in `block in load'
> remote:        /tmp/build_bdc47327/vendor/bundle/ruby/2.6.0/gems/sprockets-4.0.3/lib/sprockets/loader.rb:337:in `fetch_asset_from_dependency_cache'
> remote:        /tmp/build_bdc47327/vendor/bundle/ruby/2.6.0/gems/sprockets-4.0.3/lib/sprockets/loader.rb:43:in `load'
> remote:        /tmp/build_bdc47327/vendor/bundle/ruby/2.6.0/gems/sprockets-4.0.3/lib/sprockets/cached_environment.rb:44:in `load'
> remote:        /tmp/build_bdc47327/vendor/bundle/ruby/2.6.0/gems/sprockets-4.0.3/lib/sprockets/base.rb:81:in `find_asset'
> remote:        /tmp/build_bdc47327/vendor/bundle/ruby/2.6.0/gems/sprockets-4.0.3/lib/sprockets/base.rb:88:in `find_all_linked_assets'
> remote:        /tmp/build_bdc47327/vendor/bundle/ruby/2.6.0/gems/sprockets-4.0.3/lib/sprockets/manifest.rb:125:in `each'
> remote:        /tmp/build_bdc47327/vendor/bundle/ruby/2.6.0/gems/sprockets-4.0.3/lib/sprockets/manifest.rb:125:in `to_a'
> remote:        /tmp/build_bdc47327/vendor/bundle/ruby/2.6.0/gems/sprockets-4.0.3/lib/sprockets/manifest.rb:125:in `block (2 levels) in find'
> remote:        /tmp/build_bdc47327/vendor/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/executor/safe_task_executor.rb:24:in `block in execute'
> remote:        /tmp/build_bdc47327/vendor/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:47:in `block in synchronize'
> remote:        /tmp/build_bdc47327/vendor/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:47:in `synchronize'
> remote:        /tmp/build_bdc47327/vendor/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:47:in `synchronize'
> remote:        /tmp/build_bdc47327/vendor/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/executor/safe_task_executor.rb:22:in `execute'
> remote:        /tmp/build_bdc47327/vendor/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/promise.rb:564:in `block in realize'
> remote:        /tmp/build_bdc47327/vendor/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:352:in `run_task'
> remote:        /tmp/build_bdc47327/vendor/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:343:in `block (3 levels) in create_worker'
> remote:        /tmp/build_bdc47327/vendor/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:334:in `loop'
> remote:        /tmp/build_bdc47327/vendor/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:334:in `block (2 levels) in create_worker'
> remote:        /tmp/build_bdc47327/vendor/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:333:in `catch'
> remote:        /tmp/build_bdc47327/vendor/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:333:in `block in create_worker'
> remote:        Tasks: TOP => assets:precompile
> remote:        (See full trace by running task with --trace)
> remote:
> remote:  !
> remote:  !     Precompiling assets failed.
> remote:  !
> remote:  !     Push rejected, failed to compile Ruby app.
> remote:
> remote:  !     Push failed
> remote:  !
> remote:  ! ## Warning - The same version of this code has already been built: e705a92f0507117b4994965b31f23fe1dd9aebdc
> remote:  !
> remote:  ! We have detected that you have triggered a build from source code with version e705a92f0507117b4994965b31f23fe1dd9aebdc
> remote:  ! at least twice. One common cause of this behavior is attempting to deploy code from a different branch.
> remote:  !
> remote:  ! If you are developing on a branch and deploying via git you must run:
> remote:  !
> remote:  !     git push heroku <branchname>:main
> remote:  !
> remote:  ! This article goes into details on the behavior:
> remote:  !   https://devcenter.heroku.com/articles/duplicate-build-version
> remote:
> remote: Verifying deploy...
> remote:
> remote: !	Push rejected to vtourhub-backend.
> remote:
> To https://git.heroku.com/vtourhub-backend.git
>  ! [remote rejected] create_heroku -> main (pre-receive hook declined)
> error: failed to push some refs to 'https://git.heroku.com/vtourhub-backend.git
> ```
> 

## 該当のソースコード

- app/assets/javascript/admin.js

```
//= require jquery
//= require rails-ujs
//= require admin-lte/plugins/bootstrap/js/bootstrap.bundle.min
//= require admin-lte/dist/js/adminlte.min
``` 

- config/initializers/assets.rb

```
# Be sure to restart your server when you modify this file.

# Version of your assets, change this if you want to expire all your assets.
Rails.application.config.assets.version = '1.0'

# Add additional assets to the asset load path.
# Rails.application.config.assets.paths << Emoji.images_path
# Add Yarn node_modules folder to the asset load path.
Rails.application.config.assets.paths << Rails.root.join('node_modules')

# Precompile additional assets.
# application.js, application.css, and all non-JS/CSS in the app/assets
# folder are already added.
Rails.application.config.assets.precompile += %w( admin.js admin.css )

```

## エラーから考えられる原因

> prockets::FileNotFound: couldn't find file 'admin-lte/plugins/bootstrap/js/bootstrap.bundle.min' with type 'application/javascript'

エラー文の上記の部分から、`node_modules/`直下に保存されているAdminLTEのプラグインが読み込まれていないことが原因だと考えました。開発環境では、読み込まれ上手く動いていたので、本番環境でも問題なく動作すると考えたのですが、そもそも、Rails APIモードでAdminLTEを導入し管理画面を表示するためのViewを作ったことが原因ではないかと考えました。

## 試したこと

エラー文で指摘されている部分の記載を削除しpushすると上手くデプロイできたが、UIが崩れており操作が可能な状態ではなかった。

## 考えられる解決方法

- Rails API（サーバ側）で管理画面を作るのではなく、Vue（フロント側）で管理画面を作成し直す

## 質問内容

- 本番環境にデプロイできない原因はRails APIで管理画面を作成しようとしていることが原因なのか？
- 上記が原因であれば、なぜ開発環境では動作するのか？
- 管理画面はVueで作成したほうが良いか？

**Comment by O-H-K-N** [comment]
## 解決方法
npm/yarnでインストールしたものをHerokuで使う場合、**node.js の buildpack を追加する必要がある。**
参考：https://zenn.dev/junki555/articles/400589974d3034

開発環境直下のパスで下記のコマンドを実行すると解決した。
```
heroku buildpacks:add --index 1 heroku/nodejs
```


## situmonnniついての解答

> 本番環境にデプロイできない原因はRails APIで管理画面を作成しようとしていることが原因なのか？
> 上記が原因であれば、なぜ開発環境では動作するのか？

それが原因ではない。

> 管理画面はVueで作成したほうが良いか？
サーバ側でOK！
